### ISSUE TITLE
Public agent additional ports not exposed on public agent ELB

### ISSUE THREAD

**Issue by jimmidyson** [dcos-terraform/terraform-aws-dcos#23]
I've added an additional port via `public_agents_additional_ports` to my deployment, the port is listed in the public agent's security group, but the ELB isn't configured to expose it - is that expected? What can i do to fix that? This seems like a bug, but could be expected behaviour.

**Comment by fatz** [comment]
with elb's we currently can't use this feature as the terraform resource is not accepting the generated list of hashes in the elb resource.

As we've to support alb anyways I started working on those

**Comment by jimmidyson** [comment]
Hey @fatz! How's this going?

**Comment by fatz** [comment]
this is not as easy as I thought. Still working on a lb ( nlb + alb ) module there will be quite some changes. I expect to have an update next week

**Comment by fatz** [comment]
@jimmidyson so as I said in the comment before I was not able to add this feature to the current ELB based setup. We have a working version with LB / ALB / NLB but this means we have to deploy a new minor version of the whole AWS module as changing this backend will be a breaking change to existing clusters.

**Comment by jimmidyson** [comment]
@fatz Hey! Any update on this? Can we maybe use your branch until this is rolled out widely?

**Comment by fatz** [comment]
@jimmidyson sorry sure. Did not realise that there is no link in here. I just created a WIP PR for that check it out here: dcos-terraform/terraform-aws-infrastructure#13

**Comment by jimmidyson** [comment]
Thanks! We'll try it out!

**Comment by fatz** [comment]
rebased... feel free to try it out

**Comment by sebbrandt87** [comment]
solved @jimmidyson ?

**Comment by jimmidyson** [comment]
Solved in v0.2.0, yes, thanks!

Shame this means we have to choose between coreos support (v0.1.x only) and properly exposing additional public agent ports... but that's life!
