### ISSUE TITLE
Feature Request: Public Agent LB Security Groups: Allowed IP Ranges

### ISSUE THREAD

**Issue by shaneutt** [dcos-terraform/terraform-aws-dcos#40]
Currently you can use `admin_ips` to manage the admin firewall and restrict access to DC/OS. However it doesn't appear that you can provide IP ranges for access to the public agents.

The purpose of this issue is to request that a separate variable be added which would allow explicit declaration of which IP ranges may access the public agents.

**Comment by geekbass** [comment]
Closing the issue.
