### ISSUE TITLE
rexray_config_preset missing

### ISSUE THREAD

**Issue by Rohithzr** [dcos-terraform/terraform-aws-dcos#63]
I think we need to add this option, if there is no existing method.
doc link: 
https://docs.mesosphere.com/1.12/installing/production/advanced-configuration/configuration-reference/#rexray-config-preset

**Comment by Rohithzr** [comment]
actually it would be best if we can have a wildcard/regex like support to add custom configs to be passed.
something like
`dcos_config_*`  where everything at `*` will be passed to dcos config.

**Comment by rohithzr** [comment]
we can add it like this,
```
dcos_config=<<EOF
rexray_config_preset: aws
EOF
```
